- name: Container is running
  docker:
    state: reloaded
    restart_policy: always
    image: wordpress
    name: blog
    links:
      - db:mysql
    log_driver: syslog
    log_opt:
      syslog-tag: blog
  tags: [blog]
