elk_keypair: "cake"
elk_security_group: ""
elk_instance_type: "t2.micro"
elk_image: "ami-fce3c696"
elk_subnet_ids: ['subnet-REDACTED','subnet-REDACTED','subnet-REDACTED']
elk_region: "us-east-1"
elk_tag_Name: "elk"
elk_tag_Type: "elk"
elk_tag_Environment: "production"
elk_volume_size: 16

blog_keypair: "cake"
blog_security_group: ""
blog_instance_type: "t2.micro"
blog_image: "ami-fce3c696"
blog_subnet_ids: ['subnet-REDACTED','subnet-REDACTED','subnet-REDACTED']
blog_region: "us-east-1"
blog_tag_Name: "blog"
blog_tag_Type: "blog"
blog_tag_Environment: "production"
blog_volume_size: 16
