---
 - hosts: tag_Name_elk
   user: ubuntu
   become: yes
   pre_tasks:
    - include_vars: group_vars/elk.yml
   roles:
    - docker
    - elasticsearch
    - logstash
    - kibana
    - { role: nginx, conf_file: "elk.conf",container_name: "kibana" }
