---
 - hosts: all
   tasks: []
   user: ubuntu

 - hosts: tag_Name_blog
   user: ubuntu
   become: yes
   pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - group_vars/elk.yml
        - group_vars/blog.yml
   roles:
    - docker
    - db
    - blog
    - rsyslog
    - { role: nginx, conf_file: "blog.conf",container_name: "blog" }
