- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [kibana]

- name: Container is running
  docker:
    image: kibana
    name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
  register: kibana_result
  tags: [kibana]
#TODO: Fix the code below so it won't override the default kibana discovery page
#- name: Create kibana index
#  uri:
#    url: "http://{{ elk_ip }}:9200/.kibana"
#    status_code: [200,201]
#    method: PUT
#    body: "{{ lookup('file', 'kibana-index.json') }}"
#    body_format: json
#    HEADER_Content-Type: "application/json"

#- name: Create Visualizations
#  uri:
#    url: "http://{{ elk_ip }}:9200/.kibana/visualization/{{ item }}"
#    status_code: [200,201]
#    method: PUT
#    body: "{{ lookup('file', item +'.json') }}"
#    body_format: json
#    HEADER_Content-Type: "application/json"
#  with_items:
#      - Traffic-by-Country-ampersand-Device
#      - Traffic-by-Country-ampersand-OS
#      - Unique-Visits-by-City
#      - Total-Hits-by-City
#      - Traffic-vs.-Location
#      - Total-Visitors
#      - Unique-Visitors
#      - Apache-Dashboard
#- name: Create Dashboard
#  uri:
#    url: "http://{{ elk_ip }}:9200/.kibana/dashboard/{{ item }}"
#    status_code: [200,201]
#    method: PUT
#    body: "{{ lookup('file', item +'.json') }}"
#    body_format: json
#    HEADER_Content-Type: "application/json"
#  with_items:
#      - Apache
