- name: Directories are present
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [logstash]

- name: Config file is present
  copy:
    src: syslog.conf
    dest: "{{ conf_dir }}/syslog.conf"
  tags: [logstash]

- name: Container is running
  docker:
    state: reloaded
    image: logstash
    name: logstash
    volumes:
      - "{{ conf_dir }}:/conf"
    expose:
      - 25826
    ports:
      - 25826:25826
      - 25826:25826/udp
    links:
      - elasticsearch

    command: "/bin/bash -c 'logstash-plugin install logstash-input-cloudwatch; logstash -f /conf/syslog.conf'"
  tags: [logstash]
